version: '3.9'
services:
  pulsopus_postgres:
    image: postgres:latest
    container_name: 'pulsopus_postgres'
    restart: always
    env_file: .env.production
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'pulsopus_db'
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  pulsopus_api:
    build: .
    container_name: 'pulsopus_api'
    env_file: .env.production
    restart: always
    depends_on:
      - pulsopus_postgres
    links:
      - "pulsopus_postgres:postgres"
    ports:
      - "8080:8080"

volumes:
  pgdata:

networks:
  postgres:
    driver: bridge
